### ISSUE TITLE
property_exists(): Passing null to parameter #2 ($property) of type string is deprecated

### ISSUE THREAD

**Issue by s1lver** [pozitronik/yii2-badgewidget#5]
**PHP 8.1.3**

```
2022-02-24 09:48:06 [192.168.221.1][1][dceae57faac1d86ec3c685a67d8227af][error][yii\base\ErrorException:8192] yii\base\ErrorException: property_exists(): Passing null to parameter #2 ($property) of type string is deprecated in /var/www/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php:201
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(8192, 'property_exists...', '/var/www/vendor...', 201)
#1 /var/www/vendor/yiisoft/yii2/helpers/BaseArrayHelper.php(201): property_exists(Object(yii\base\DynamicModel), NULL)
#2 /var/www/vendor/pozitronik/yii2-helpers/src/ArrayHelper.php(36): yii\helpers\BaseArrayHelper::getValue(Object(yii\base\DynamicModel), NULL, NULL)
#3 /var/www/vendor/pozitronik/yii2-badgewidget/src/BadgeWidget.php(268): pozitronik\helpers\ArrayHelper::getValue(Object(yii\base\DynamicModel), NULL)
#4 /var/www/vendor/pozitronik/yii2-badgewidget/src/BadgeWidget.php(470): pozitronik\widgets\BadgeWidget->prepareValue(Object(yii\base\DynamicModel))
#5 /var/www/vendor/yiisoft/yii2/base/Widget.php(146): pozitronik\widgets\BadgeWidget->run()
```

**Comment by s1lver** [comment]
Вызываем виджет в любом месте, например:

```php
BadgeWidget::widget([
    'items' => $user->username,
    'innerPrefix' => $user->isAllPermissionsGranted()
	?'<i class="fas fa-crown color-danger-500" title="All permissions granted via config"></i>'
	:false
])
```

На PHP 8.1 получаем ошибку

> property_exists(): Passing null to parameter # 2 ($property) of type string is deprecated

**Comment by pozitronik** [comment]
> Вызываем виджет в любом месте, например:
> 
> ```
> BadgeWidget::widget([
>     'items' => $user->username,
>     'innerPrefix' => $user->isAllPermissionsGranted()
> 	?'<i class="fas fa-crown color-danger-500" title="All permissions granted via config"></i>'
> 	:false
> ])
> ```
> 
> На PHP 8.1 получаем ошибку
> 
> > property_exists(): Passing null to parameter # 2 ($property) of type string is deprecated

У тебя вызов некорректный. Нужно:
```php
BadgeWidget::widget([
    'items' => $user,
    'subItems' => 'username',
    'innerPrefix' => $user->isAllPermissionsGranted()
	?'<i class="fas fa-crown color-danger-500" title="All permissions granted via config"></i>'
	:false
])
```

**Comment by pozitronik** [comment]
Стал разбираться: в Yii параметр `$key` типизирован в PHPDoc как `string|\Closure|array`, т.е. null реально не допускается. Несмотря на отсутствие strict-типизации, мы обязаны соблюдать эту сигнатуру.
Хотя в виджете ошибки всё ещё нет, я добавлю исключение на случай некорректного вызова.

**Comment by pozitronik** [comment]
[Исправлено  тут](https://github.com/pozitronik/yii2-helpers/commit/6449ddb1a354c8382a6caba022d30c4a0755219a).
